# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 13:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0)),
                ('comment', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('tag_type', models.CharField(choices=[('course', 'course'), ('tag', 'tag')], default='tag', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable'), ('booked', 'booked')], default='available', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='UserAccount.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='UserAccount.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='UserAccount.UserProfile')),
                ('tutor_id', models.CharField(max_length=30, unique=True)),
                ('tutor_type', models.CharField(choices=[('contracted', 'contracted'), ('private', 'private')], default='contracted', max_length=30)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('tags', models.ManyToManyField(to='UserAccount.Tag')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccount.University')),
            ],
        ),
        migrations.AddField(
            model_name='timeslot',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccount.Tutor'),
        ),
        migrations.AddField(
            model_name='review',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccount.Tutor'),
        ),
    ]
