# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0002_auto_20171123_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='searchable',
            field=models.BooleanField(default=True),
        ),
    ]
