# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Wallet', '0001_initial'),
        ('Bookings', '0001_initial'),
        ('UserAccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wallet.Wallet'),
        ),
        migrations.AddField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccount.Student'),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserAccount.TimeSlot'),
        ),
    ]
